/**
 * API for an application of projects and todos
 * This is a sample API for a simple application of projects and their respective todos. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Additional message for the root error.
 */
export interface AdditionalMessage { 
    /**
     * Error code of the (error) message.
     */
    id: string;
    /**
     * Descriptive text for the message.
     */
    description?: string;
    /**
     * Severity enum of the error message.
     */
    severity: AdditionalMessage.SeverityEnum;
    /**
     * An optional help URI.
     */
    help_uri?: string;
    /**
     * An optional path.
     */
    path?: string;
}
export namespace AdditionalMessage {
    export type SeverityEnum = 'error' | 'warning' | 'information';
    export const SeverityEnum = {
        Error: 'error' as SeverityEnum,
        Warning: 'warning' as SeverityEnum,
        Information: 'information' as SeverityEnum
    };
}


