/**
 * API for an application of projects and todos
 * This is a sample API for a simple application of projects and their respective todos. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdditionalMessage } from './additionalMessage';


export interface ModelError { 
    /**
     * Descriptive text of the error.
     */
    error: string;
    /**
     * Descriptive text of the error.
     */
    error_description?: string;
    /**
     * An optional error URI.
     */
    error_uri?: string;
    /**
     * The causing request ID.
     */
    request_id?: string;
    /**
     * Array of additional messages.
     */
    additional_messages?: Array<AdditionalMessage>;
}

