/**
 * API for an application of projects and todos
 * This is a sample API for a simple application of projects and their respective todos. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TodoItem { 
    /**
     * Unique technical ID of the TodoItem.
     */
    id?: number;
    /**
     * Title of the TodoItem - what has to be done
     */
    title: string;
}

