apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
  labels:
    app.kubernetes.io/name: getting-started
spec:
  selector:
    matchLabels:
      app: getting-started
  replicas: 1
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
      - name: getting-started
        image: danglm/getting-started
        ports:
        - containerPort: 3000
          name: http-gs
---
apiVersion: v1
kind: Service
metadata:
  name: getting-started
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-gs
  selector:
    app: getting-started
